[package]
name = "panther-ffi"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
anyhow.workspace = true
once_cell.workspace = true
ffi-support.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tokio.workspace = true
panther-domain = { path = "../panther-domain" }
panther-core = { path = "../panther-core" }
panther-providers = { path = "../panther-providers" }
panther-observability = { path = "../panther-observability" }
panthersdk = { path = "../../panthersdk" }
panther-agents = { path = "../panther-agents", optional = true }
<<<<<<< HEAD
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"], optional = true }
=======
>>>>>>> origin/main

[features]
default = []
metrics-inmemory = ["dep:panther-metrics"]
metrics-prometheus = ["dep:panther-metrics", "panther-metrics/prometheus-exporter"]
storage-inmemory = ["dep:panther-storage"]
storage-sled = ["dep:panther-storage-sled"]
metrics = ["metrics-inmemory"]
storage = ["storage-inmemory"]
observability = []
validation = ["dep:panther-validation"]
validation-openai = ["validation", "panther-validation/openai"]
validation-ollama = ["validation", "panther-validation/ollama"]
validation-anthropic = ["validation", "panther-validation/anthropic"]
blockchain-eth = ["validation", "panther-validation/blockchain-eth", "panther-agents/blockchain-eth"]
validation-async = ["validation"]
validation-openai-async = ["validation-async", "panther-validation/openai-async", "panther-providers/openai-async"]
validation-ollama-async = ["validation-async", "panther-validation/ollama-async", "panther-providers/ollama-async"]
validation-anthropic-async = ["validation-async", "panther-validation/anthropic-async", "panther-providers/anthropic-async"]
agents = ["dep:panther-agents"]
agents-openai = ["agents", "panther-agents/validation-openai"]
agents-ollama = ["agents", "panther-agents/validation-ollama"]
agents-openai-async = ["agents", "panther-agents/validation-openai-async"]
agents-ollama-async = ["agents", "panther-agents/validation-ollama-async"]
<<<<<<< HEAD
guidelines-embed-openai = ["dep:reqwest"]
guidelines-embed-ollama = ["dep:reqwest"]
=======
>>>>>>> origin/main

[dependencies.panther-metrics]
path = "../panther-metrics"
optional = true

[dependencies.panther-storage]
path = "../panther-storage"
optional = true

[dependencies.panther-storage-sled]
path = "../panther-storage-sled"
optional = true

[dependencies.panther-validation]
path = "../panther-validation"
optional = true
