[package]
name = "panther-ai-eval"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
panther-validation = { path = "../panther-validation", default-features = false, features = ["openai", "ollama"] }

[features]
default = ["openai", "ollama"]
openai = []
ollama = []

