name: PantherSampleSwift
options:
  deploymentTarget:
    iOS: '16.0'
targets:
  PantherSampleSwift:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
          - GENERATE_PROJECT.sh
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.panthersampleswift
      SWIFT_VERSION: 5.0
      INFOPLIST_FILE: Info.plist
      SWIFT_OBJC_BRIDGING_HEADER: Bridging-Header.h
      HEADER_SEARCH_PATHS:
        - $(SRCROOT)/../../bindings/include
        - $(SRCROOT)/../../target/aarch64-apple-ios-sim/release
      LIBRARY_SEARCH_PATHS:
        - $(SRCROOT)/../../target/aarch64-apple-ios-sim/release
    dependencies:
      - sdk: libc++.tbd
    settingsOverrides:
      OTHER_LDFLAGS: ["-lpanther_ffi"]
