[package]
name = "panther-metrics"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
panther-domain = { path = "../panther-domain" }

[features]
default = []
prometheus-exporter = ["dep:prometheus"]

[dependencies.prometheus]
version = "0.13"
optional = true
